data "aws_ami" "latest_amazon_linux" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

resource "aws_security_group" "jenkins_sg" {
  name        = "jenkins-sg-${var.environment}"
  description = "Jenkins web UI and agent access"
  vpc_id      = var.vpc_id

  ingress {
    description = "Jenkins UI from admin IP only"
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = [var.admin_ip_cidr]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name        = "jenkins-sg-${var.environment}"
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

data "aws_iam_policy_document" "jenkins_assume_role" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "jenkins_role" {
  name               = "jenkins-role-${var.environment}"
  assume_role_policy = data.aws_iam_policy_document.jenkins_assume_role.json

  tags = {
    Environment = var.environment
  }
}

# Broad for now — same as the OIDC role, tighten once the pipeline is proven out
data "aws_iam_policy_document" "jenkins_permissions" {
  statement {
    actions = [
      "s3:*",
      "ec2:*",
      "iam:*",
      "dynamodb:*",
    ]
    resources = ["*"]
  }
}

resource "aws_iam_role_policy" "jenkins_policy" {
  name   = "jenkins-policy-${var.environment}"
  role   = aws_iam_role.jenkins_role.id
  policy = data.aws_iam_policy_document.jenkins_permissions.json
}

resource "aws_iam_instance_profile" "jenkins_profile" {
  name = "jenkins-profile-${var.environment}"
  role = aws_iam_role.jenkins_role.name
}

resource "aws_instance" "jenkins" {
  ami                    = data.aws_ami.latest_amazon_linux.id
  instance_type          = var.instance_type
  subnet_id              = var.subnet_id
  vpc_security_group_ids = [aws_security_group.jenkins_sg.id]
  iam_instance_profile   = aws_iam_instance_profile.jenkins_profile.name
  user_data              = file("${path.module}/scripts/install_jenkins.sh")

  tags = {
    Name        = "jenkins-${var.environment}"
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

resource "random_password" "jenkins_admin" {
  length  = 20
  special = true
}

resource "aws_secretsmanager_secret" "jenkins_admin" {
  name        = "jenkins-admin-password-${var.environment}"
  description = "Jenkins initial admin password, generated by Terraform"

  tags = {
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "jenkins_admin" {
  secret_id     = aws_secretsmanager_secret.jenkins_admin.id
  secret_string = random_password.jenkins_admin.result
}